export const routes = {
  LOGIN: 'login',
  REGISTER: 'register',
  CONFIRM: 'confrim-email',
  REGISTER_DETAILS: 'register-details',
  REGISTERION_PENDING: 'regesterion-pending',
  FORGOT_PASSWORD: 'reset-password',
  ALL_STORES: "stores/all-stores",
  TRANSFER_MEDICINES: "stores/transfer-medicnes",
  ALL_MEDICINES: "medicines/all-medicines",
  STORE_MEDICINES: "medicines/store",
  REPORT_MEDICINE: "medicines/report-medicine",
  SUPPLIERS: "suppliers",
  SEND_ORDER: "send-order",
  OUTGOING_ORDERS: "orders/outgoing-orders",
  PURCHASE_ORDERS: "orders/received-orders/purchase-orders",
  RETURN_ORDERS: "orders/received-orders/return-orders",
  EXPRESS_ORDERS: "orders/express-orders",
  INVOICES: "orders/invoices",
  ANALYTICS: "analytics",
  REPORTS: "reports",
  SETTINGS: "settings",
};
